### ISSUE TITLE
Package does not support Sound Null Safety

### ISSUE THREAD

**Issue by coder-Aayush** [piyushmaurya23/eva_icons_flutter#5]
### Error Reproduce
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:fleva_icons

For solutions, see https://dart.dev/go/unsound-null-safety

Unhandled exception:
Bad state: Unsupported Null Safety mode NonNullableByDefaultCompiledMode.Invalid, in null.
# 0      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:435:9)

# 1      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:144:33)
# 2      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:632:20)
<asynchronous suspension>
# 3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:545:9)

<asynchronous suspension>
# 4      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1105:11)
<asynchronous suspension>

the Dart compiler exited unexpectedly.
Exited (sigterm)
Failed to compile application.

**Comment by karan413255** [comment]
The package now supports null-safety #4
